@base_auth = http://localhost:8000/api/v1/auth
@base_api  = http://localhost:8000/api/v1
@pwd = Test1234!
@ts = {{$timestamp}}
@email = bob{{ts}}@example.com


### Register — 201
# @name register
POST {{base_auth}}/register/
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{pwd}}",
  "first_name": "Bob",
  "last_name": "Dupont",
  "age": 28,
  "native_langs": ["fr"],
  "target_langs": ["en"],
  "consent_given": true
}


### Me direct — 200 (token de register)
GET {{base_auth}}/me/
Authorization: Bearer {{register.response.body.$.access}}


### Refresh — 200 (depuis refresh du register)
# @name refresh
POST {{base_auth}}/refresh/
Content-Type: application/json

{
  "refresh": "{{register.response.body.$.refresh}}"
}


### Login — 200 (réutilise l’email et le pwd)
# @name login
POST {{base_auth}}/login/
Content-Type: application/json
Authorization:

{
  "email": "{{register.response.body.$.email}}",
  "password": "{{pwd}}"
}


### Me après login — 200 (token de login)
GET {{base_auth}}/me/
Authorization: Bearer {{login.response.body.$.access}}


############################################################
#                    MÉTIER (Events / Bookings)
############################################################

### Languages — 200
# @name languages
GET {{base_api}}/languages/
Authorization: Bearer {{login.response.body.$.access}}

### Partners — 200
# @name partners
GET {{base_api}}/partners/
Authorization: Bearer {{login.response.body.$.access}}

### Create Event — 201
# @name create_event
POST {{base_api}}/events/
Authorization: Bearer {{login.response.body.$.access}}
Content-Type: application/json

{
  "partner": {{partners.response.body.$.results[0].id}},
  "language": "{{languages.response.body.$.results[0].code}}",
  "theme": "Afterwork test",
  "difficulty": "easy",
  "datetime_start": "2025-09-05T18:00:00Z",
  "price_cents": 700
}

### Event detail — 200
GET {{base_api}}/events/{{create_event.response.body.$.id}}/
Authorization: Bearer {{login.response.body.$.access}}

### Create Booking — 201
# @name create_booking
POST {{base_api}}/bookings/
Authorization: Bearer {{login.response.body.$.access}}
Content-Type: application/json

{
  "event": {{create_event.response.body.$.id}}
}

### My Bookings — 200
GET {{base_api}}/bookings/
Authorization: Bearer {{login.response.body.$.access}}

### Cancel Booking (autorisé jusqu'à T-3h) — 200 ou 400
POST {{base_api}}/bookings/{{create_booking.response.body.$.id}}/cancel/
Authorization: Bearer {{login.response.body.$.access}}
