# Generated by Django 5.2.5 on 2025-08-17 18:02

import bookings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_harden_booking_constraints"),
        ("events", "0003_alter_event_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_booking_per_user_event",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_bo_event_i_f8e449_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_bo_user_id_69a5d5_idx",
        ),
        migrations.AlterField(
            model_name="booking",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="expires_at",
            field=models.DateTimeField(default=bookings.models.default_expiry),
        ),
        migrations.AlterField(
            model_name="booking",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["public_id"], name="bookings_bo_public__c31fe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="bookings_bo_status_233e96_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "event"], name="bookings_bo_user_id_917bf5_idx"
            ),
        ),
    ]
