# Generated by Django 5.2.5 on 2025-08-18 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_alter_booking_options_and_more"),
        ("events", "0003_alter_event_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="booking_quantity_gte_1",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_bo_public__c31fe1_idx",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="booking",
            name="amount_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="currency",
            field=models.CharField(default="EUR", max_length=8),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_intent_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("user", "event"),
                name="unique_pending_booking_per_user_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CONFIRMED")),
                fields=("user", "event"),
                name="unique_confirmed_booking_per_user_event",
            ),
        ),
    ]
