# Generated by Django 5.2.7 on 2025-10-05 20:19

import bookings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_remove_booking_booking_quantity_gte_1_and_more"),
        ("events", "0005_add_max_participants_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="amount_cents",
            field=models.PositiveIntegerField(
                default=0, help_text="Amount paid in cents (e.g., 700 = 7.00€)"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, help_text="When booking was cancelled", null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="confirmed_after_expiry",
            field=models.BooleanField(
                default=False,
                help_text="Whether booking was confirmed after expiration time",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When booking was confirmed (payment successful)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="currency",
            field=models.CharField(
                default="EUR", help_text="Currency code (ISO 4217)", max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="event",
            field=models.ForeignKey(
                help_text="Event being booked",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="expires_at",
            field=models.DateTimeField(
                default=bookings.models.default_expiry,
                help_text="When PENDING booking expires (default 15 minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_intent_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe PaymentIntent ID (for confirmed bookings)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Public UUID for external references (Stripe, etc.)",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                help_text="Current booking status",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                help_text="User who made this booking",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
