# Generated by Django 5.2.8 on 2025-11-16 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_add_organizer_booking_field"),
        ("events", "0015_update_booking_unique_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_pending_booking_per_user_event",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELLED"), _negated=True),
                fields=("user", "event"),
                name="unique_active_booking_per_user_event",
            ),
        ),
    ]
