# Generated by Django 5.2.5 on 2025-08-13 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("venue_name", models.CharField(max_length=140)),
                ("city", models.CharField(max_length=80)),
                ("address", models.CharField(max_length=200)),
                ("datetime_start", models.DateTimeField()),
                ("max_seats", models.PositiveSmallIntegerField(default=6)),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="languages.language",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["datetime_start"],
                "indexes": [
                    models.Index(
                        fields=["datetime_start"], name="events_even_datetim_840454_idx"
                    )
                ],
            },
        ),
    ]
