# Generated by Django 5.2.5 on 2025-08-16 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("languages", "0001_initial"),
        ("partners", "0004_alter_partner_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="address",
        ),
        migrations.RemoveField(
            model_name="event",
            name="city",
        ),
        migrations.RemoveField(
            model_name="event",
            name="is_cancelled",
        ),
        migrations.RemoveField(
            model_name="event",
            name="title",
        ),
        migrations.RemoveField(
            model_name="event",
            name="venue_name",
        ),
        migrations.AddField(
            model_name="event",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Facile"),
                    ("medium", "Moyen"),
                    ("hard", "Difficile"),
                ],
                default="easy",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="partner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="partners.partner",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="event_photos/"),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("finished", "Terminé"),
                    ("cancelled", "Annulé"),
                    ("full", "Complet"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="theme",
            field=models.CharField(default="A_definir", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="price_cents",
            field=models.PositiveIntegerField(default=700),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="events_even_status_5709b6_idx"),
        ),
    ]
