# Generated by Django 5.2.5 on 2025-08-17 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_event_address_remove_event_city_and_more"),
        ("languages", "0001_initial"),
        ("partners", "0004_alter_partner_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-datetime_start"]},
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="events_even_datetim_840454_idx",
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="events_even_status_5709b6_idx",
        ),
        migrations.RemoveField(
            model_name="event",
            name="max_seats",
        ),
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=255
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=160
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Débutant"),
                    ("medium", "Intermédiaire"),
                    ("hard", "Avancé"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="price_cents",
            field=models.PositiveIntegerField(default=700, editable=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="theme",
            field=models.CharField(max_length=120),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["partner", "datetime_start"],
                name="events_even_partner_a31410_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["language", "datetime_start"],
                name="events_even_languag_2c376a_idx",
            ),
        ),
    ]
