# Generated by Django 5.2.7 on 2025-10-05 20:19

import django.db.models.deletion
import events.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_add_max_participants_field"),
        ("languages", "0001_initial"),
        ("partners", "0004_alter_partner_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-datetime_start"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Auto-generated from partner address",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, help_text="When event was cancelled", null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="datetime_start",
            field=models.DateTimeField(
                help_text="Event start date and time (must be at least 2h in future)",
                validators=[events.validators.validate_event_datetime],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Beginner"),
                    ("medium", "Intermediate"),
                    ("hard", "Advanced"),
                ],
                help_text="Difficulty level for this event",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="language",
            field=models.ForeignKey(
                help_text="Primary language practiced at this event",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="languages.language",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                help_text="User who created and organized this event",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="partner",
            field=models.ForeignKey(
                help_text="Venue where event takes place",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="partners.partner",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Event cover photo",
                null=True,
                upload_to="events/",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="price_cents",
            field=models.PositiveIntegerField(
                default=700,
                editable=False,
                help_text="Price per participant in cents (7.00€ = 700 cents)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When event was published (after payment)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("AWAITING_PAYMENT", "Awaiting Payment"),
                    ("PUBLISHED", "Published"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                help_text="Current event status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="theme",
            field=models.CharField(
                help_text="Event theme or topic (e.g., 'French Culture', 'Business English')",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Auto-generated from partner name",
                max_length=160,
            ),
        ),
    ]
