# Generated by Django 5.2.7 on 2025-10-07 (manual)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_options_alter_event_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="max_participants",
        ),
    ]
