# Generated by Django 5.2.7 on 2025-10-08 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_remove_max_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Beginner"),
                    ("medium", "Intermediate"),
                    ("hard", "Advanced"),
                ],
                help_text="Difficulty level for this event (max 10 chars)",
                max_length=10,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        10, message="Difficulty must be 10 characters or less"
                    )
                ],
            ),
        ),
    ]
