# Generated by Django 5.2.7 on 2025-11-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_add_registration_workflow_fields"),
        ("events", "0008_add_field_validators"),
    ]

    operations = []
