# Generated by Django 5.2.7 on 2025-11-03 18:09

import events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_merge_20251101_2046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="datetime_start",
            field=models.DateTimeField(
                help_text="Event start date and time (must be at least 3h in future)",
                validators=[events.validators.validate_event_datetime],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="price_cents",
            field=models.PositiveIntegerField(
                default=700,
                editable=False,
                help_text="Price per participant in cents (7.00ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ = 700 cents)",
            ),
        ),
    ]
