# Generated by Django 5.2.7 on 2025-11-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_remove_awaiting_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="game_difficulty",
            field=models.CharField(
                blank=True,
                help_text="Pre-configured game difficulty (easy, medium, hard)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="game_started",
            field=models.BooleanField(
                default=False,
                help_text="Whether the game has been started by the organizer",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="game_timeout_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                default=5,
                help_text="Pre-configured game timeout in minutes (default: 5)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="game_type",
            field=models.CharField(
                blank=True,
                help_text="Pre-configured game type (e.g., 'picture_description', 'word_association')",
                max_length=32,
                null=True,
            ),
        ),
    ]
