# Generated by Django 5.2.8 on 2025-11-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_remove_game_difficulty_timeout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="game_type",
            field=models.CharField(
                blank=True,
                help_text="Pre-configured game type (e.g., 'picture_description', 'word_association'). Uses event's language and difficulty.",
                max_length=32,
                null=True,
            ),
        ),
    ]
