version: "3.9"

services:

  # PostgreSQL Database
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: conversadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Django Backend (Gunicorn)
  backend:
    build: ./backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_NAME=conversadb
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres
      - DJANGO_DB_HOST=db

  # React Frontend (Nginx)
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

# 📦 Docker named volume for persistent database storage
volumes:
  postgres_data:
