# Generated by Django 5.2.7 on 2025-11-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="game",
            new_name="games_game_event_i_c6f3f7_idx",
            old_name="games_game_event_i_idx",
        ),
        migrations.RenameIndex(
            model_name="game",
            new_name="games_game_status_cda4c5_idx",
            old_name="games_game_status_idx",
        ),
        migrations.RenameIndex(
            model_name="gamevote",
            new_name="games_gamev_game_id_f4d93b_idx",
            old_name="games_gamev_game_id_idx",
        ),
    ]
