# Generated by Django 5.2.8 on 2025-11-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_add_options_and_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="correct_answer",
            field=models.CharField(
                help_text="Correct answer key for current question", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Optional image URL for current question",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="question_id",
            field=models.CharField(
                help_text="ID of the current question from JSON file", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="question_text",
            field=models.TextField(help_text="The current question text"),
        ),
    ]
