# Generated by Django 5.2.8 on 2025-11-12 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_alter_game_correct_answer_alter_game_image_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("victory", "Victory"),
                            ("participation", "Participation"),
                        ],
                        help_text="Type of badge earned",
                        max_length=20,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="GameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(
                        help_text="Total number of questions in game"
                    ),
                ),
                (
                    "correct_answers",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of questions answered correctly"
                    ),
                ),
                (
                    "score_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of correct answers (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("victory", "Victory"),
                            ("participation", "Participation"),
                        ],
                        help_text="Type of badge earned",
                        max_length=20,
                    ),
                ),
                (
                    "victory_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Percentage needed for victory badge (default 50%)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Game Result",
                "verbose_name_plural": "Game Results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="gamevote",
            name="unique_vote_per_user_per_game",
        ),
        migrations.AddField(
            model_name="gamevote",
            name="question_id",
            field=models.CharField(
                default="unknown",
                help_text="ID of the question from JSON file",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="gamevote",
            name="question_index",
            field=models.PositiveIntegerField(
                default=0, help_text="Index of the question this vote is for (0-based)"
            ),
        ),
        migrations.AddIndex(
            model_name="gamevote",
            index=models.Index(
                fields=["game", "question_index"], name="games_gamev_game_id_7d9731_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gamevote",
            constraint=models.UniqueConstraint(
                fields=("game", "user", "question_index"),
                name="unique_vote_per_user_per_question",
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="user",
            field=models.ForeignKey(
                help_text="User who earned this badge",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_badges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gameresult",
            name="game",
            field=models.OneToOneField(
                help_text="Game this result is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="game_result",
            field=models.ForeignKey(
                help_text="Game result this badge is from",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badges",
                to="games.gameresult",
            ),
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(
                fields=["user", "badge_type"], name="games_badge_user_id_2028d3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="badge",
            constraint=models.UniqueConstraint(
                fields=("game_result", "user"), name="unique_badge_per_user_per_game"
            ),
        ),
    ]
