# compose.dev.yml — ajoute toutes les variables d’environnement
services:
  db:
    env_file:
      - ./env/.env.dev
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME}
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
