version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: conversadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data_ci:/var/lib/postgresql/data

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
      args:
        CI_MODE: "true"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_DB_NAME: conversadb
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: postgres
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: config.settings.test
      DJANGO_SECRET_KEY: dummy
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DJANGO_DEBUG: "False"

volumes:
  postgres_data_ci:
