services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - conversa
    environment:
      POSTGRES_DB: conversadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
      args:
        REQUIREMENTS_FILE: requirements/dev.txt
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - conversa

  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
      target: dev
    ports:
      - "5173:5173"
    networks:
      - conversa

volumes:
  postgres_data:
  node_modules_frontend:

networks:
  conversa:
    external: {}