services:
  backend:
    env_file:
      - ./env/.env.dev
    volumes:
      - ../backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    env_file:
      - ./env/.env.dev
    volumes:
      - ../frontend:/app
      - node_modules_frontend:/app/node_modules
      
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./env/.env.dev
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - conversa
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@conversa.local
      PGADMIN_DEFAULT_PASSWORD: changeme