services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data_ci:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DJANGO_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DJANGO_DB_NAME:-conversadb}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - conversa

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
      args:
        REQUIREMENTS_FILE: requirements/dev.txt
    entrypoint: ["/entrypoint.ci.sh"]
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DJANGO_SECRET_KEY: dummy
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DJANGO_DB_NAME: conversadb
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD:-postgres}
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - conversa


volumes:
  postgres_data_ci:

networks:
  conversa: {}
