# ==============================================================================
# Docker Compose - Production Environment (PROD)
# ------------------------------------------------------------------------------
# This file is used to run the Conversa application in production.
# Docker images are assumed to be pre-built and stored on GHCR.
# Sensitive variables to be injected from the environment (Render, GitHub Actions, etc.)
# ==============================================================================

services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY,,}-backend:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
      DJANGO_DB_HOST: ${DJANGO_DB_HOST}
      DJANGO_DB_PORT: ${DJANGO_DB_PORT}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ENV_MODE: ${ENV_MODE}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
      DJANGO_SU_NAME: ${DJANGO_SU_NAME}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
    entrypoint: ["/entrypoints/entrypoint.prod.sh"]
    networks:
      - conversa

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY,,}-frontend:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - conversa

networks:
  conversa: