# ==============================================================================
# Docker Compose - Continuous Integration (CI)
# ------------------------------------------------------------------------------
# Utilisé dans les workflows GitHub Actions (CI/CD)
# - Lance uniquement le backend Django avec SQLite (pas de base PostgreSQL)
# - Toutes les variables sont injectées par GitHub Secrets
# ==============================================================================

services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
      args:
        REQUIREMENTS_FILE: requirements/ci.txt
    environment:
      ENV_MODE: ${ENV_MODE}
      DEBUG: ${CI_DEBUG}
      SECRET_KEY: ${CI_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: ${CI_DJANGO_SETTINGS_MODULE}
      CI_DJANGO_ALLOWED_HOSTS: ${CI_DJANGO_ALLOWED_HOSTS}
      CI_DJANGO_SU_NAME: ${CI_DJANGO_SU_NAME}
      CI_DJANGO_SU_PASSWORD: ${CI_DJANGO_SU_PASSWORD}
      CI_DJANGO_SU_EMAIL: ${CI_DJANGO_SU_EMAIL}
