FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY backend/requirements /requirements
RUN pip install --upgrade pip && pip install -r /requirements/dev.txt

COPY backend /app
COPY docker/entrypoint.ci.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
