# Generated by Django 5.2.5 on 2025-08-18 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_remove_booking_booking_quantity_gte_1_and_more"),
        ("payments", "0002_alter_payment_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_status_7ad4af_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_created_b8a300_idx",
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="bookings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="EUR", max_length=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("succeeded", "succeeded"),
                    ("failed", "failed"),
                    ("canceled", "canceled"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="payments_pa_stripe__6fe52c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "booking"], name="payments_pa_user_id_b129f3_idx"
            ),
        ),
    ]
