# Generated by Django 5.2.5 on 2025-08-20 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_remove_booking_booking_quantity_gte_1_and_more"),
        ("payments", "0003_alter_payment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="raw_event",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_cents",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["stripe_checkout_session_id"],
                name="payments_pa_stripe__6a75d6_idx",
            ),
        ),
    ]
