# Generated by Django 5.2.7 on 2025-10-08 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cleanup_currency_codes(apps, schema_editor):
    """
    Cleanup currency codes to ensure they fit in 3 characters.
    Truncates any currency > 3 chars and converts to uppercase.
    """
    Payment = apps.get_model('payments', 'Payment')

    # Get all payments with currency length > 3
    long_currencies = Payment.objects.exclude(currency__regex=r'^[A-Z]{3}$')

    count = 0
    for payment in long_currencies:
        old_currency = payment.currency
        # Truncate to 3 chars and uppercase
        payment.currency = str(old_currency).upper().strip()[:3] if old_currency else 'EUR'
        payment.save(update_fields=['currency'])
        count += 1

    if count > 0:
        print(f"Cleaned up {count} currency codes to 3-char ISO format")


def reverse_cleanup(apps, schema_editor):
    """No reverse operation needed - truncation is irreversible."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_allow_multiple_confirmed_bookings"),
        (
            "payments",
            "0004_payment_raw_event_payment_stripe_checkout_session_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # FIRST: Clean up existing data
        migrations.RunPython(cleanup_currency_codes, reverse_cleanup),

        # THEN: Apply schema changes
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_cents",
            field=models.IntegerField(default=0, help_text="Payment amount in cents"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                help_text="Associated booking",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="bookings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default="EUR",
                help_text="Currency code (ISO 4217 - 3 letter code)",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="raw_event",
            field=models.JSONField(
                blank=True,
                help_text="Latest Stripe webhook event (for audit trail)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                help_text="Payment status",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Checkout Session ID",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Payment Intent ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                help_text="User who made the payment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
