# Generated by Django 5.2.7 on 2025-10-08 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_payment_options_alter_payment_amount_cents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default="EUR",
                help_text="Currency code (ISO 4217 - 3 letter code, e.g., EUR)",
                max_length=3,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, message="Currency must be a 3-letter ISO code"
                    ),
                    django.core.validators.MaxLengthValidator(
                        3, message="Currency must be a 3-letter ISO code"
                    ),
                    django.core.validators.RegexValidator(
                        message="Currency must be 3 uppercase letters (e.g., EUR, USD, GBP)",
                        regex="^[A-Z]{3}$",
                    ),
                ],
            ),
        ),
    ]
