# Generated by Django 5.2.7 on 2025-11-03 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_add_field_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount_cents",
            field=models.IntegerField(
                default=0,
                help_text="Payment amount in cents (negative for refunds)",
                validators=[
                    django.core.validators.MinValueValidator(
                        -1000000,
                        message="Amount cannot be less than -1,000,000 cents (-10,000 EUR)",
                    ),
                    django.core.validators.MaxValueValidator(
                        1000000,
                        message="Amount cannot exceed 1,000,000 cents (10,000 EUR)",
                    ),
                ],
            ),
        ),
    ]
