# Generated by Django 5.2.5 on 2025-08-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="google_maps_url",
        ),
        migrations.AddField(
            model_name="partner",
            name="capacity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partner",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
