# Generated by Django 5.2.5 on 2025-08-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_remove_partner_google_maps_url_partner_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="city",
            field=models.CharField(default="Bruxelles", max_length=100),
            preserve_default=False,
        ),
    ]
