# Generated by Django 5.2.5 on 2025-08-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_partner_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="city",
            field=models.CharField(default="Bruxelles", max_length=100),
        ),
    ]
