# Generated by Django 5.2.7 on 2025-11-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_alter_partner_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={
                "ordering": ["name"],
                "verbose_name": "Partner Venue",
                "verbose_name_plural": "Partner Venues",
            },
        ),
        migrations.AlterField(
            model_name="partner",
            name="address",
            field=models.CharField(help_text="Street address", max_length=500),
        ),
        migrations.AlterField(
            model_name="partner",
            name="api_key",
            field=models.CharField(
                editable=False,
                help_text="Unique API key for partner integration",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="capacity",
            field=models.PositiveIntegerField(
                default=0, help_text="Maximum seats available"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="city",
            field=models.CharField(
                default="Brussels", help_text="City name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether venue accepts events"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(help_text="Venue name", max_length=255),
        ),
        migrations.AlterField(
            model_name="partner",
            name="reputation",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                help_text="Rating out of 5.0",
                max_digits=2,
            ),
        ),
    ]
