# Generated by Django 4.2.27 on 2025-12-14 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0005_alter_partner_options_alter_partner_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='owner',
            field=models.OneToOneField(blank=True, help_text='User who owns this partner (assigned by admin). Owner has exclusive access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
