# Generated by Django 5.2.4 on 2025-08-06 17:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Adresse email utilisée comme identifiant principal pour la connexion.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Prénom réel de l’utilisateur.", max_length=150
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Nom réel de l’utilisateur.", max_length=150
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        help_text="Date de naissance de l’utilisateur (obligatoire pour vérifier la majorité)."
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Texte libre pour décrire son parcours ou ses centres d’intérêt.",
                    ),
                ),
                (
                    "language_native",
                    models.CharField(
                        help_text="Langue maternelle principale déclarée par l’utilisateur.",
                        max_length=100,
                    ),
                ),
                (
                    "languages_spoken",
                    models.JSONField(
                        default=list,
                        help_text="Liste de langues parlées par l’utilisateur (au moins niveau conversationnel).",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date d’inscription sur la plateforme.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date de dernière modification du profil utilisateur.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Permet de désactiver temporairement ou définitivement un compte sans le supprimer.",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si l’utilisateur a accès à l’interface d’administration Django.",
                    ),
                ),
                (
                    "is_partner",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si l’utilisateur est partenaire (bar, lieu ou organisateur reconnu).",
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False,
                        help_text="Consentement explicite donné par l’utilisateur lors de l’inscription (RGPD).",
                    ),
                ),
                (
                    "is_profile_public",
                    models.BooleanField(
                        default=True,
                        help_text="Le profil de l’utilisateur est-il visible par les autres membres ?",
                    ),
                ),
                (
                    "jwt_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Clé de révocation utilisée pour invalider les tokens JWT.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Les groupes auxquels cet utilisateur appartient.",
                        related_name="custom_user_groups",
                        to="auth.group",
                        verbose_name="groupes",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Les permissions spécifiques de cet utilisateur.",
                        related_name="custom_user_permissions",
                        to="auth.permission",
                        verbose_name="permissions d’utilisateur",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
