# Generated by Django 5.2.4 on 2025-08-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Identifiant public",
                max_length=150,
                null=True,
                unique=True,
            ),
        ),
    ]
