# Generated by Django 5.2.5 on 2025-08-11 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
        ("users", "0002_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="languages_wanted",
            field=models.JSONField(
                default=list,
                help_text="(DEPRECATED) Langues à apprendre (codes) au format JSON. Remplacé par 'wanted_languages'.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="native_language",
            field=models.ForeignKey(
                blank=True,
                help_text="Langue maternelle (référence vers 'languages.Language').",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="native_users",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="spoken_languages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Langues parlées (référence vers 'languages.Language').",
                related_name="spoken_users",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="wanted_languages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Langues à apprendre (référence vers 'languages.Language').",
                related_name="wanted_users",
                to="languages.language",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language_native",
            field=models.CharField(
                help_text="(DEPRECATED) Langue maternelle au format texte. Remplacé par 'native_language'.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="languages_spoken",
            field=models.JSONField(
                default=list,
                help_text="(DEPRECATED) Langues parlées (codes) au format JSON. Remplacé par 'spoken_languages'.",
            ),
        ),
    ]
