# Generated by Django 5.2.5 on 2025-08-11 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
        ("users", "0003_user_languages_wanted_user_native_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="language_native",
        ),
        migrations.RemoveField(
            model_name="user",
            name="languages_spoken",
        ),
        migrations.RemoveField(
            model_name="user",
            name="languages_wanted",
        ),
        migrations.AlterField(
            model_name="user",
            name="native_language",
            field=models.ForeignKey(
                blank=True,
                help_text="Langue maternelle (référence Language).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="native_users",
                to="languages.language",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="spoken_languages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Langues parlées (référence Language).",
                related_name="spoken_users",
                to="languages.language",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Identifiant public.",
                max_length=150,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="wanted_languages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Langues que l’utilisateur souhaite apprendre (référence Language).",
                related_name="wanted_users",
                to="languages.language",
            ),
        ),
    ]
