# Generated by Django 5.2.7 on 2025-11-03 18:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0002_alter_language_options_alter_language_code_and_more"),
        ("users", "0005_user_consent_given_user_consent_given_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="revokedaccesstoken",
            options={
                "ordering": ["-revoked_at"],
                "verbose_name": "Revoked Access Token",
                "verbose_name_plural": "Revoked Access Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelOptions(
            name="usertargetlanguage",
            options={
                "ordering": ["user", "language"],
                "verbose_name": "User Target Language",
                "verbose_name_plural": "User Target Languages",
            },
        ),
        migrations.AlterField(
            model_name="revokedaccesstoken",
            name="jti",
            field=models.CharField(
                db_index=True,
                help_text="JWT ID (jti claim) of the revoked token",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="revokedaccesstoken",
            name="revoked_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when token was revoked"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, help_text="Street address", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(
                help_text="User's age (minimum 18)",
                validators=[django.core.validators.MinValueValidator(18)],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(blank=True, help_text="Avatar image URL"),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="User biography (max 500 characters)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, help_text="City", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="consent_given",
            field=models.BooleanField(
                default=False, help_text="User has given consent for data processing"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="consent_given_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when consent was given", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country code (e.g., BE)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date user joined the platform",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="User's email address (login)",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(help_text="User's first name", max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, help_text="User account is active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False, help_text="User can access admin site"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(help_text="User's last name", max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude for geolocation",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude for geolocation",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="native_langs",
            field=models.ManyToManyField(
                help_text="Languages the user speaks natively",
                related_name="native_users",
                to="languages.language",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(help_text="Hashed password", max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="target_langs",
            field=models.ManyToManyField(
                help_text="Languages the user wants to learn",
                related_name="target_users",
                through="users.UserTargetLanguage",
                to="languages.language",
            ),
        ),
        migrations.AlterField(
            model_name="usertargetlanguage",
            name="language",
            field=models.ForeignKey(
                help_text="Language being learned",
                on_delete=django.db.models.deletion.CASCADE,
                to="languages.language",
            ),
        ),
        migrations.AlterField(
            model_name="usertargetlanguage",
            name="user",
            field=models.ForeignKey(
                help_text="User learning the language",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
