# Generated by Django 5.2.7 on 2025-11-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_rebuild_auditlog_with_categories"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_created_6e540c_idx",
            old_name="audit_audit_created_cd2419_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_categor_529cbb_idx",
            old_name="audit_audit_categor_f2fc31_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_level_788d83_idx",
            old_name="audit_audit_level_6f23d7_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_user_id_429f6b_idx",
            old_name="audit_audit_user_id_9c6c44_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_action_86e815_idx",
            old_name="audit_audit_action_7b4a85_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_resourc_2a3aef_idx",
            old_name="audit_audit_resourc_e3d912_idx",
        ),
    ]
