name: CI/CD

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Django checks (SQLite)
    runs-on: ubuntu-latest
    env:
      ENV_MODE: ci
      DJANGO_SETTINGS_MODULE: config.settings.ci
      SECRET_KEY: test-secret
      DEBUG: "0"
    steps:
      - uses: actions/checkout@v4

      - id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-pip-

      - name: Install CI deps
        run: |
          pip install --upgrade pip
          pip install -r requirements/ci.txt

      - name: Django checks + migrations (SQLite)
        run: |
          python backend/manage.py check --deploy
          python backend/manage.py makemigrations --check --dry-run
          python backend/manage.py migrate --noinput

  migrate_and_deploy:
    name: Migrate DB (Render) + Deploy
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-pip-

      - name: Install PROD deps
        run: |
          pip install --upgrade pip
          pip install -r requirements/prod.txt

      - name: Preflight env check
        run: |
          python - <<'PY'
          import os, sys
          required = [
            'SECRET_KEY','DJANGO_ALLOWED_HOSTS',
            'DJANGO_DB_NAME','DJANGO_DB_USER','DJANGO_DB_PASSWORD','DJANGO_DB_HOST','DJANGO_DB_PORT'
          ]
          missing = [k for k in required if not os.getenv(k)]
          if missing:
              print("Missing env:", ", ".join(missing))
              sys.exit(2)
          print("All required env present.")
          PY
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
          DJANGO_DB_NAME: ${{ secrets.DJANGO_DB_NAME }}
          DJANGO_DB_USER: ${{ secrets.DJANGO_DB_USER }}
          DJANGO_DB_PASSWORD: ${{ secrets.DJANGO_DB_PASSWORD }}
          DJANGO_DB_HOST: ${{ secrets.DJANGO_DB_HOST }}
          DJANGO_DB_PORT: ${{ secrets.DJANGO_DB_PORT }}

      - name: Run Django migrations on Render Postgres
        working-directory: backend
        env:
          DJANGO_SETTINGS_MODULE: config.settings.prod
          DEBUG: "0"
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
          DJANGO_DB_NAME: ${{ secrets.DJANGO_DB_NAME }}
          DJANGO_DB_USER: ${{ secrets.DJANGO_DB_USER }}
          DJANGO_DB_PASSWORD: ${{ secrets.DJANGO_DB_PASSWORD }}
          DJANGO_DB_HOST: ${{ secrets.DJANGO_DB_HOST }}
          DJANGO_DB_PORT: ${{ secrets.DJANGO_DB_PORT }}
        run: |
          python manage.py migrate --noinput --fake-initial

      - name: Trigger Render deploy (backend)
        if: ${{ success() }}
        run: curl -X POST "$RENDER_DEPLOY_HOOK_BACKEND_URL"
        env:
          RENDER_DEPLOY_HOOK_BACKEND_URL: ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND_URL }}

      - name: Trigger Render deploy (frontend)
        if: ${{ success() }}
        run: curl -X POST "$RENDER_DEPLOY_HOOK_FRONTEND_URL"
        env:
          RENDER_DEPLOY_HOOK_FRONTEND_URL: ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND_URL }}
