name: Build & Test (CI)

on:
  push:
    branches: 
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_DB_PASSWORD: ${{ secrets.DJANGO_DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests via Docker Compose
        run: |
          docker compose -f docker/compose.base.yml -f docker/compose.ci.yml up --build --exit-code-from backend
