name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Déclencher Render via webhook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
