name: Deploy to Render

on:
  workflow_dispatch:  # Lancement manuel uniquement

jobs:
  deploy:
    name: Deploy backend to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Require tests to pass
        uses: actions/github-script@v7
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test.yml',
              branch: 'main',
              status: 'completed'
            });

            const latest = runs.data.workflow_runs.find(run => run.conclusion === 'success');
            if (!latest || latest.head_sha !== context.sha) {
              core.setFailed('Les tests n’ont pas encore passé avec succès sur ce commit.');
            }

      - name: Trigger Render Deploy Hook
        run: |
          curl -X GET "https://api.render.com/deploy/srv-d24137ndiees73a4uv40?key=z9IIQZ5MXOQ"
