# Generated by Django 5.2.5 on 2025-08-11 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 639-1 code (e.g., fr, en, nl).",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use a 2-letter ISO 639-1 lowercase code (e.g. 'fr', 'en').",
                                regex="^[a-z]{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "names",
                    models.JSONField(
                        default=dict,
                        help_text="Labels by locale, e.g. {'fr':'Français','en':'French','nl':'Frans'}.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Langue",
                "verbose_name_plural": "Langues",
                "ordering": ["sort_order", "code"],
            },
        ),
    ]
