# Generated by Django 5.2.7 on 2025-11-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={
                "ordering": ["sort_order", "code"],
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="ISO 639-1 language code (e.g., 'fr', 'en', 'nl')",
                max_length=8,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when language was added"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this language is available for selection",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="label_en",
            field=models.CharField(
                help_text="Language name in English (e.g., 'French')", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="label_fr",
            field=models.CharField(
                help_text="Language name in French (e.g., 'Français')", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="label_nl",
            field=models.CharField(
                help_text="Language name in Dutch (e.g., 'Frans')", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="sort_order",
            field=models.PositiveSmallIntegerField(
                default=100, help_text="Display order (lower numbers appear first)"
            ),
        ),
    ]
